#
# DRIVE
#
DriveTank:
  deadzone: .15
  leftMultiplier: 120.0
  rightMultiplier: 120.0
  exponent: 2.0

DriveArcade:
  deadzone: .1
  speedMultiplier: 120.0
  rotateMultiplier: 120.0
  exponent: 2.0

#
# PICKER
#
PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

PickerPick:
  control:
    pick: 1.0
    pinch: 0.75
    highPower: 1.0
    lowPower: .25
    highTolerance: 50.0
    stopTolerance: 1.0
  ballAgeThresholds:
#    0.0: OLD
    0.0: AGED
    0.5: NEW
#    0.0: AGED
  dataLogging: false
  targetBallDistance: 48.0

PickerShortPick:
  pick: 1.0
  pinch: 1.0
  minBallDistance: 250.0

PickerBarf:
  pick: -1.0
  pinch: -1.0
  king: -1.0

PickerCheval:

#
# TURRET
#
HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

TurretShoot:
  kingRollerPower: 1.0
  waitTimeout: 2.0
  shootTime: 1.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 75.0

TurretTarget:
  wheelSpeeds:
    NEW:
      0: 5200
      72: 4900
      84: 4900
      144: 5200
    AGED:
      0: 5000
      72: 4800
      84: 4800
      144: 5000
    OLD:
      0: 5000
      72: 4800
      84: 4800
      144: 5000
  hoodPositions:
    NEW:
      0: UP1
      72: UP2
      82: UP4
    AGED:
      0: UP1
      72: UP2
      82: UP4
    OLD:
      0: UP1
      72: UP2
      82: UP4
  dataLogging: false
  startDelay: .25

TurretBatter:
  class: TurretPrep
  lights: false
  wheelSpeed: 5000
  hoodPosition: UP1
  turretAngle: 0.0

TurretCalibrate:
  class: TurretPrep
  lights: true
  wheelSpeed: 4800

TurretBarfPrep:
  class: TurretPrep
  wheelSpeed: 3600.0

TurretBatter:
  class: TurretPrep
  wheelSpeed: 4800

TurretBumpLeft:
  class: TurretBumpRotation
  angle: -10.0

TurretBumpRight:
  class: TurretBumpRotation
  angle: 10.0

TurretStraight:
  class: TurretSetRotation
  angle: 0.0

TurretRight:
  class: TurretSetRotation
  angle: 75.0

TurretLeft:
  class: TurretSetRotation
  angle: -75.0

TurretBumpWheelSpeedUp:
  class: TurretBumpWheelSpeedOffset
  offset: 50 # 100

TurretBumpWheelSpeedDown:
  class: TurretBumpWheelSpeedOffset
  offset: -50 # -100

#
# AUTON
#
^DriveStraight:
  speed: 40.0
  angleController: { type: PID, P: 4.8 }

DriveStraightCheval:
  speed: -30.0
  angleController: { type: PID, P: 4.8 }

^DriveRotate:
  angleController:
    type: PID
    P: 3.5
    I: 3.5
    maxIError: 10.0
    maxAbsoluteOutput: 48.0
    target: { within: 1.5, time: .125 }

$SequentialTest:
  - class: DriveStraight
    speed: 40.0
    angle: 0.0
    distance: 36.0
  - class: DriveRotate
    angle: 90.0
  - class: DriveStraight
    speed: 40.0
    angle: 90.0
    distance: 36.0
  - class: DriveRotate
    angle: 180.0
  - class: DriveStraight
    speed: 40.0
    angle: 180.0
    distance: 36.0
  - class: DriveRotate
    angle: 270.0
  - class: DriveStraight
    speed: 40.0
    angle: 270.0
    distance: 36.0
  - class: DriveRotate
    angle: 360.0

$AutoShoot:
  - name: TurretTarget
    parallel: true
  - class: WaitCommand
    period: 2.0
  - TurretShoot

$AutoLowBarPickRotate:
  - PickerPick
  - class: TurretSetRotation
    angle: 42.0

$AutoLowBar:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: DriveStraight
    speed: 80.0
    angle: 0.0
    distance: 192.0
  - $AutoShoot

$AutoLowBar2Ball:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: TurretSetRotation
    angle: 42.0
    parallel: true
  - class: DriveStraight
    speed: 60.0
    angle: 0.0
    distance: 60.0
  - class: DriveStraight
    speed: 100.0
    angle: 0.0
    distance: 120.0
  - $AutoShoot
  - class: DriveStraight
    speed: -100.0
    angle: 0.0
    distance: 144.0
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: DriveStraight
    speed: -80.0
    angle: -15.0
    distance: 60.0
  - class: DriveStraight
    speed: 80.0
    angle: -15.0
    distance: 48.0
  - class: DriveStraight
    speed: 60.0
    angle: 0.0
    distance: 60.0
  - class: DriveStraight
    speed: 100.0
    angle: 0.0
    distance: 84.0
  - $AutoShoot
#  - class: DriveStraight
#    speed: -80.0
#    angle: 0.0
#    distance: 192.0

$AutoRockWall2:
  - PickerPick
  - PickerToCheval
  - class: TurretSetRotation
    angle: 45.0
    parallel: true
  - class: DriveStraight
    speed: 80.0
    angle: 0.0
    distance: 240.0
  - PickerToPick
  - $AutoShoot

$AutoMoat3PickRotate:
  - PickerPick
  - class: TurretSetRotation
    angle: 25.0

$AutoMoat3:
  - PickerPick
  - PickerToCheval
  - class: TurretSetRotation
    angle: 10.0
    parallel: true
  - class: DriveStraight
    speed: 80.0
    angle: 0.0
    distance: 168.0
  - PickerToPick
  - $AutoShoot

$AutoCheval4:
  - PickerPick
  - class: TurretSetRotation
    angle: 90.0
    parallel: true
  - PickerToCheval
  - DriveStraightCheval
  - PickerToPick
  - class: DriveStraight
    speed: -40.0
    angle: 0.0
    distance: 36.0
  - PickerToCheval
  - class: DriveStraight
    speed: -40.0
    angle: 0.0
    distance: 72.0
  - class: DriveRotate
    angle: 90.0
  - PickerToPick
  - $AutoShoot

$AutoRamparts5:
  - PickerPick
  - PickerToCheval
  - class: TurretSetRotation
    angle: -45.0
    parallel: true
  - class: DriveStraight
    speed: 80.0
    angle: 0.0
    distance: 264.0
  - PickerToPick
  - $AutoShoot

AutoChooser:
  class: ChooserCommand
  commands:
    - $AutoShoot
    - $AutoLowBar
    - $AutoLowBar2Ball
    - $AutoRockWall2
    - $AutoMoat3
    - $AutoCheval4
    - $AutoRamparts5
    - $SequentialTest

$AutoInit:
  - TurretHome
  - AutoChooser
