DriveTank:
  deadzone: .05
  multiplier: 1.0
  exponent: 2.0

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

PickerPick:
  pickRoller: 1.0
  pinchRoller: 1.0
  kingRoller: 0.5
  ballDistance: 50

TurretShoot:
  kingRollerPower: 1.0
  timeout: 2.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 66.0

TurretTarget:
  ledPower: 1.0
  wheelSpeed: 91
