DriveTank:
  deadzone: .1
  leftMultiplier: 100.0
  rightMultiplier: 100.0
  exponent: 2.0

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

PickerPick:
  control:
    pick: 1.0
    pinch: 0.75
    highPower: 1.0
    lowPower: .25
    highTolerance: 50.0
    stopTolerance: 1.0
  targetBallDistance: 48.0
  compression:
    start: 75.0
    stop: 57.0
    newBallThreshold: .424
  dataLogging: true

PickerBarf:
  pick: -1.0
  pinch: -1.0
  king: -1.0

TurretShoot:
  kingRollerPower: 1.0
  waitTimeout: 2.0
  shootTime: 1.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 75.0

TurretShootPrep:
  class: TurretPrep
  target: true
  wheelSpeeds:
    0: 88.333
#    120: 91.666
    120: 90.0
  hoodPositions:
    0: UP4
    120: UP4
  dataLogging: false

TurretBarfPrep:
  class: TurretPrep
  target: false
  wheelSpeeds:
    0: 60.0

TurretCalibrate:
  class: TurretPrep
  lights: true
  wheelSpeeds:
    0: 0

TurretBumpLeft:
  class: TurretBumpRotation
  angle: -10.0

TurretBumpRight:
  class: TurretBumpRotation
  angle: 10.0

TurretBumpWheelSpeedUp:
  class: TurretBumpWheelSpeedOffset
  offset: 1.666666666666666666666666666666666

TurretBumpWheelSpeedDown:
  class: TurretBumpWheelSpeedOffset
  offset: -1.666666666666666666666666666666666

^DriveStraight:
  power: 0.2
  angleController: { type: PID, P: 4.8 }

^DriveRotate:
  angleController:
    type: PID
    P: 2.4
    I: 2.4
    maxIError: 10.0
    maxAbsoluteOutput: 48.0
    target: { within: 1.0, time: .125 }

$SequentialTest:
  - class: DriveStraight
    power: 40.0
    targetAngle: 0.0
    distance: 36.0
  - class: DriveRotate
    angle: 90.0
  - class: DriveStraight
    power: 40.0
    targetAngle: 90.0
    distance: 36.0
  - class: DriveRotate
    angle: 180.0
  - class: DriveStraight
    power: 40.0
    targetAngle: 180.0
    distance: 36.0
  - class: DriveRotate
    angle: 270.0
  - class: DriveStraight
    power: 40.0
    targetAngle: 270.0
    distance: 36.0
  - class: DriveRotate
    angle: 360.0

$AutoShoot:
  - name: TurretShootPrep
    parallel: true
  - class: WaitCommand
    period: 2.0
  - TurretShoot

$AutoLowBarPickRotate:
  - PickerPick
  - class: TurretSetRotation
    angle: 42.0

$AutoLowBar:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: TurretSetRotation
    angle: 42.0
    parallel: true
  - class: DriveStraight
    power: 40.0
    targetAngle: 0.0
    distance: 192.0
  - $AutoShoot

$Auto2Ball:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: TurretSetRotation
    angle: 42.0
    parallel: true
  - class: DriveStraight
    power: 40.0
    targetAngle: 0.0
    distance: 192.0
  - $AutoShoot
  - class: DriveStraight
    power: -40.0
    targetAngle: 0.0
    distance: 144.0
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: DriveStraight
    power: -40.0
    targetAngle: -10.0
    distance: 60.0
  - class: DriveStraight
    power: 40.0
    targetAngle: -10.0
    distance: 60.0
  - class: DriveStraight
    power: 40.0
    targetAngle: 0.0
    distance: 144.0
  - $AutoShoot
  - class: DriveStraight
    power: -40.0
    targetAngle: 0.0
    distance: 192.0


AutoInit:
  class: CommandChooser
  commands:
    - $AutoShoot
    - $Auto2Ball
    - $AutoLowBar
    - $SequentialTest
