DriveTank:
  deadzone: .15
  leftMultiplier: 120.0
  rightMultiplier: 120.0
  exponent: 2.0

DriveArcade:
  deadzone: .1
  speedMultiplier: 120.0
  rotateMultiplier: 120.0
  exponent: 2.0

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

PickerPick:
  control:
    pick: 1.0
    pinch: 0.75
    highPower: 1.0
    lowPower: .25
    highTolerance: 50.0
    stopTolerance: 1.0
  targetBallDistance: 48.0
  ballAgeThresholds:
    0.0: OLD
    0.4: AGED
    0.5: NEW
#    0.0: AGED
  dataLogging: false

PickerBarf:
  pick: -1.0
  pinch: -1.0
  king: -1.0

PickerCheval:

TurretShoot:
  kingRollerPower: 1.0
  waitTimeout: 2.0
  shootTime: 1.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 75.0

TurretTarget:
  wheelSpeeds:
    NEW:
      0: 5400
      60: 5400
      72: 5300
      84: 5200
    AGED:
      0: 5300
      60: 5300
      72: 5200
      84: 5200
    OLD:
      0: 5200
      60: 5200
      72: 5100
      84: 5200
  hoodPositions:
    NEW:
      0: UP4
    AGED:
      0: UP4
    OLD:
      0: UP4
  dataLogging: false

TurretBarfPrep:
  class: TurretPrep
  wheelSpeed: 3600.0

TurretCalibrate:
  class: TurretPrep
  lights: true
  wheelSpeed: 5100

TurretBumpLeft:
  class: TurretBumpRotation
  angle: -10.0

TurretBumpRight:
  class: TurretBumpRotation
  angle: 10.0

TurretBumpWheelSpeedUp:
  class: TurretBumpWheelSpeedOffset
  offset: 50 # 100

TurretBumpWheelSpeedDown:
  class: TurretBumpWheelSpeedOffset
  offset: -50 # -100

^DriveStraight:
  speed: 40.0
  angleController: { type: PID, P: 4.8 }

^DriveRotate:
  angleController:
    type: PID
    P: 2.4
    I: 2.4
    maxIError: 10.0
    maxAbsoluteOutput: 48.0
    target: { within: 1.0, time: .125 }

$SequentialTest:
  - class: DriveStraight
    speed: 40.0
    angle: 0.0
    distance: 36.0
  - class: DriveRotate
    angle: 90.0
  - class: DriveStraight
    speed: 40.0
    angle: 90.0
    distance: 36.0
  - class: DriveRotate
    angle: 180.0
  - class: DriveStraight
    speed: 40.0
    angle: 180.0
    distance: 36.0
  - class: DriveRotate
    angle: 270.0
  - class: DriveStraight
    speed: 40.0
    angle: 270.0
    distance: 36.0
  - class: DriveRotate
    angle: 360.0

$AutoShoot:
  - name: TurretTarget
    parallel: true
  - class: WaitCommand
    period: 2.0
  - TurretShoot

$AutoLowBarPickRotate:
  - PickerPick
  - class: TurretSetRotation
    angle: 42.0

$AutoLowBar:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: DriveStraight
    speed: 40.0
    angle: 0.0
    distance: 192.0
  - $AutoShoot

$Auto2Ball:
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: TurretSetRotation
    angle: 42.0
    parallel: true
  - class: DriveStraight
    speed: 40.0
    angle: 0.0
    distance: 192.0
  - $AutoShoot
  - class: DriveStraight
    speed: -40.0
    angle: 0.0
    distance: 144.0
  - name: $AutoLowBarPickRotate
    parallel: true
  - class: DriveStraight
    speed: -40.0
    angle: -10.0
    distance: 60.0
  - class: DriveStraight
    speed: 40.0
    angle: -10.0
    distance: 60.0
  - class: DriveStraight
    speed: 40.0
    angle: 0.0
    distance: 144.0
  - $AutoShoot
  - class: DriveStraight
    speed: -40.0
    angle: 0.0
    distance: 192.0

$AutoMoat3PickRotate:
  - PickerPick
  - class: TurretSetRotation
    angle: 25.0

$AutoMoat3:
  - name: $AutoMoat3PickRotate
    parallel: true
  - class: DriveStraight
    speed: 80.0
    angle: 0.0
    distance: 144.0
  - $AutoShoot

AutoChooser:
  class: ChooserCommand
  commands:
    - $AutoShoot
    - $Auto2Ball
    - $AutoLowBar
    - $AutoMoat3
    - $SequentialTest
