TestCommand:
  maxCount: 3
$Null:
^LogCommand:
  message: This is the default LogCommand message!
$Sequence:
  - $Null
  - class: LogCommand
    message: Before TestCommand
  - TestCommand
  - class: LogCommand
    message: After TestCommand
  - class: LogCommand