DriveTank:

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: HoodSetPosition
  hoodPosition: DOWN

HoodUp1:
  class: HoodSetPosition
  hoodPosition: UP1

HoodUp2:
  class: HoodSetPosition
  hoodPosition: UP2

HoodUp3:
  class: HoodSetPosition
  hoodPosition: UP3

HoodUp4:
  class: HoodSetPosition
  hoodPosition: UP4

TurretHome:
  speed: .15

TurretShoot:
  kingRollerPower: 0.7
  timeout: 4

PickerPick:
  pickRoller: 1.0
  pinchRoller: 1.0
  kingRoller: 0.5
  ballDistance: 50
