DriveTank:
  deadzone: .1
  leftMultiplier: 100.0
  rightMultiplier: 100.0
  exponent: 2.0

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

PickerPick:
  pickRoller: 1.0
  pinchRoller: 0.75
  kingRoller: 1.0
  ballDistance: 50

TurretShoot:
  kingRollerPower: 1.0
  waitTimeout: 2.0
  shootTime: 1.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 75.0

TurretShootPrep:
  class: TurretPrep
  target: true
  wheelSpeeds:
    0: 85
  hoodPositions:
    0: UP1
    120: UP4
  dataLogging: false

TurretBarfPrep:
  class: TurretPrep
  target: false
  wheelSpeeds:
    0: 60.0

TurretCalibrate:
  class: TurretPrep
  lights: true
  wheelSpeeds:
    0: 0

TurretBumpLeft:
  class: TurretBumpRotation
  angle: -10.0

TurretBumpRight:
  class: TurretBumpRotation
  angle: 10.0

TurretBumpWheelSpeedUp:
  class: TurretBumpWheelSpeedOffset
  offset: 5

TurretBumpWheelSpeedDown:
  class: TurretBumpWheelSpeedOffset
  offset: -5

^DriveStraight:
  power: 0.2
  angleController: { type: PID, P: 0.0375 }

^DriveRotate:
  angleController:
    type: PID
    P: 0.02
    I: 0.02
    maxIError: 10.0
    maxAbsoluteOutput: 0.4
    target: { within: 1.0, time: .125 }

$SequentialTest:
  - class: DriveRotate
    angle: 90.0
  - class: DriveStraight
    power: 0.1
    targetAngle: 90.0
    distance: 24.0

AutoInit:
  class: CommandChooser
  commands:
    - PickerToCheval
    - PickerToHome
    - PickerToPick
