DriveTank:

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK
