DriveTank:
  deadzone: .05
  multiplier: 1.0
  exponent: 2.0

PickerToHome:
  class: PickerSetPosition
  pickerPosition: HOME

PickerToCheval:
  class: PickerSetPosition
  pickerPosition: CHEVAL

PickerToPick:
  class: PickerSetPosition
  pickerPosition: PICK

HoodDown:
  class: TurretSetHoodPosition
  hoodPosition: DOWN

HoodUp1:
  class: TurretSetHoodPosition
  hoodPosition: UP1

HoodUp2:
  class: TurretSetHoodPosition
  hoodPosition: UP2

HoodUp3:
  class: TurretSetHoodPosition
  hoodPosition: UP3

HoodUp4:
  class: TurretSetHoodPosition
  hoodPosition: UP4

HoodBumpUp:
  class: TurretBumpHoodPosition
  direction: up

HoodBumpDown:
  class: TurretBumpHoodPosition
  direction: down

TurretHome:
  speed: .15

PickerPick:
  pickRoller: 1.0
  pinchRoller: 0.75
  kingRoller: 1.0
  ballDistance: 50

TurretShoot:
  kingRollerPower: 1.0
  waitTimeout: 2.0
  shootTime: 1.0

TurretStopWheel:
  class: TurretSetWheelSpeed
  speed: 0.0

TurretSpinUp:
  class: TurretSetWheelSpeed
  speed: 75.0

TurretShootPrep:
  class: TurretPrep
  target: true
  wheelSpeed: 85
  dataLogging: true

TurretBarfPrep:
  class: TurretPrep
  target: false
  wheelSpeed: 60.0

TurretBumpLeft:
  class: TurretBumpRotation
  angle: -10.0

TurretBumpRight:
  class: TurretBumpRotation
  angle: 10.0

^DriveStraight:
  power: 0.2
  angleController: { type: PID, P: 0.0375 }

$SequentialTest:
  - class: WaitCommand
    period: 3.0
  - class: DriveStraight
    targetAngle: 0.0
    distance: 10.0
  - class: WaitCommand
    period: 3.0
  - class: DriveStraight
    targetAngle: 0.0
    distance: 10.0

AutoInit:
  class: CommandChooser
  commands:
    - PickerToCheval
    - PickerToHome
    - PickerToPick