Drive:
  wheelWidth: 26
  scrubCoef: .5
  width: 28
  length: 32
  motor:
    maxRPM: 5330
    maxTorque: 42.66 # 21.33in-lbf * 2 (2 CIMS)
    gearRatio: 15.0
    momentum: 50
    dampening: 4
  encoder: { multiplier: 25.13 } # 8 * pi
  controller: { type: PID, P: .5, F: .00641 }
  driveMode: CONTROLLER
  maxSpeed: 156.0
OperatorInterface:
Picker:
  motor: # 775Pro
    maxRPM: 18730
    maxTorque: 6.28 # 6.28in-lbf * 1 (1 775Pro)
    gearRatio: 70.0
    momentum: 50
    dampening: 4
  encoder: { multiplier: 1 }
Turret:
  shooterWheelMotor: # 2 x 775Pro
    maxRPM: 18730
    maxTorque: 12.56 # 6.28in-lbf * 2 (2 775Pro)
    gearRatio: 1.5
    momentum: 50
    dampening: 4
  shooterWheelEncoder: { multiplier: 1 }
  rotationMotor: # 1 x 550
    maxRPM: 19000
    maxTorque: 3.36 # 3.36in-lbf * 1
    gearRatio: 60
    momentum: 50
    dampening: 4
  rotationEncoder: { multiplier: 360 }
  kingRollerMotor: # 1 x 550
    maxRPM: 19000
    maxTorque: 3.36 # 3.36in-lbf * 1
    gearRatio: 40.0
    momentum: 50
    dampening: 4
  kingRollerEncoder: { multiplier: 1 }
  pinchRollerMotor: # 1 x 550
    maxRPM: 19000
    maxTorque: 3.36 # 3.36in-lbf * 1
    gearRatio: 70.0
    momentum: 50
    dampening: 4
  pinchRollerEncoder: { multiplier: 1 }
Vision: