Drive:
  leftMotor: { channel: 0, inverted: false }
  rightMotor: { channel: 1, inverted: true }
  leftEncoder: { aChannel: 2, bChannel: 3 }
  rightEncoder: { aChannel: 0, bChannel: 1 }
Picker:
  pickMotor: { channel: 2, inverted: false }
  longCylinder: 0
  shortCylinder: 1
OperatorInterface:
  driverJoystick: 0
Turret:
  shooterWheelMotor: { channel: 2, inverted: false }
  shooterWheelEncoder: { aChannel: 0, bChannel: 1 }
  shortSolenoid: 0
  longSolenoid: 1
  hoodDeploySolenoid: 2
  kingRollerMotor: { channel: 3, inverted: false }
  pinchRollerMotor: { channel: 4, inverted: false }
  turretRotationMotor: { channel: 5, inverted: false }
  turretRotationEncoder: { aChannel: 0, bChannel: 1 }
  leftLimit: { channel: 0, type: NPN }
  rightLimit: { channel: 2, type: NPN }
  centerLimit: { channel: 4, type: NPN }