Drive:
  leftMotor: { channel: 0, inverted: false }
  rightMotor: { channel: 1, inverted: true }
  leftEncoder: { aChannel: 2, bChannel: 3, reverse: true }
  rightEncoder: { aChannel: 0, bChannel: 1 }
Picker:
  pickMotor: { channel: 6, inverted: true }
  longCylinder: 4
  shortCylinder: 3
OperatorInterface:
  driverJoystick: 0
Turret:
  shooterWheelMotor: { channel: 2, inverted: false }
  shooterWheelEncoder: { aChannel: 4, bChannel: 5 }
  shortSolenoid: 2
  longSolenoid: 1
  hoodDeploySolenoid: 0
  kingRollerMotor: { channel: 3, inverted: true }
  pinchRollerMotor: { channel: 5, inverted: true }
  turretRotationMotor: { channel: 4, inverted: false }
  turretRotationEncoder: { aChannel: 6, bChannel: 7 }
  leftLimit: { channel: 11, type: NPN }
  rightLimit: { channel: 10, type: NPN }
  centerLimit: { channel: 12, type: NPN }