Drive:
  controller:
    type: PID
    P: .01
    I: 0.01
    F: .0075
    minISetpoint: 1.0
    maxIError: 12.0
    dataLogging: false
  maxSpeed: 120.0
Picker:
  pickMotor: { channel: 6, inverted: false }
  longCylinder: 4
  shortCylinder: 3
  chevalSensor: { channel: 13, type: NPN }
OperatorInterface:
  driverJoystick: 0
  gunnerJoystick: 1
Turret:
  shooterWheelController:
    type: PID
#    inputSamplesToAverage 16
    P: 0.025
    I: 0.025
    maxIError: 10.0
    F: 0.004
    minOutput: 0.0
    target: { within: 1.0 }
#    dataLogging: true
  angleController:
    type: PID
    maxAbsoluteSetpoint: 110.0
    P: .1
    D: 0
    maxAbsoluteOutput: 0.5
    target: { within: .5, stop: true }
  leftLimit: { channel: 11, type: NPN }
  rightLimit: { channel: 10, type: NPN }
  centerLimit: { channel: 12, type: NPN }
  defaultBallAge: AGED
Vision:
  ledPower: { channel: 7, inverted: false } #not finalized
  tableName: TatorVision
