Driver:
  BUMPER_LEFT: start whenReleased PickerToCheval
  BUMPER_RIGHT: start whenPressed PickerToPick
  TRIGGER_LEFT: toggle whenPressed TurretTarget
  TRIGGER_RIGHT: toggle whenPressed PickerPick
  X: toggle whenPressed PickerCheval
  Y: whilePressed PickerBarf
  B: toggle whenPressed TurretCalibrate
  A: toggle whenPressed TurretShoot
  POV_UP: start whenPressed HoodBumpUp
  POV_DOWN: start whenPressed HoodBumpDown
  POV_LEFT: start whenPressed TurretBumpLeft
  POV_RIGHT: start whenPressed TurretBumpRight
  BACK: start whenPressed PickerToHome
  START: toggle whenPressed TurretBarfPrep

Gunner:
  BUMPER_LEFT: start whenPressed TurretBumpWheelSpeedUp
  TRIGGER_LEFT: start whenPressed TurretBumpWheelSpeedDown
  POV_UP: start whenPressed HoodBumpUp
  POV_DOWN: start whenPressed HoodBumpDown
  POV_LEFT: start whenPressed TurretBumpLeft
  POV_RIGHT: start whenPressed TurretBumpRight
  BACK: start whenPressed PickerToHome
  START: toggle whenPressed TurretBarfPrep
  A: toggle whenPressed TurretShoot
  B: toggle whenPressed TurretTarget
  X: toggle whenPressed PickerPick
  Y: toggle whenReleased PickerCheval

defaults: [ DriveTank ]

