Driver:
  A: start whenPressed PickerToHome
  B: start whenReleased PickerToCheval
  Y: start whenPressed PickerToPick
  X: start whenPressed TurretHome
  POV_UP: start whenPressed HoodUp4
  POV_RIGHT: start whenPressed HoodUp1
  POV_DOWN: start whenPressed HoodDown

Gunner:
