Driver:
  BUMPER_LEFT: start whenReleased PickerToCheval
  BUMPER_RIGHT: start whenPressed PickerToPick
  TRIGGER_LEFT: toggle whenPressed TurretTarget
  TRIGGER_RIGHT: toggle whenPressed PickerPick
  Y: start whenPressed TurretStopWheel
  B: start whenPressed TurretSpinUp
  X: toggle whenPressed TurretShoot
  A: start whenPressed TurretShoot
  POV_UP: start whenPressed HoodUp4
  POV_RIGHT: start whenPressed HoodUp1
  POV_DOWN: start whenPressed HoodDown


Gunner:

defaults: [ DriveTank ]
