Driver:
  BUMPER_LEFT: start whenReleased PickerToCheval
  BUMPER_RIGHT: start whenPressed PickerToPick
  TRIGGER_LEFT: toggle whenPressed TurretShootPrep
  TRIGGER_RIGHT: toggle whenPressed PickerPick
  Y: start whenPressed TurretStopWheel
  B: toggle whenPressed TurretCalibrate
  X: toggle whenPressed TurretShoot
  A: toggle whenPressed TurretShoot
  POV_UP: start whenPressed HoodBumpUp
  POV_DOWN: start whenPressed HoodBumpDown
  POV_LEFT: start whenPressed TurretBumpLeft
  POV_RIGHT: start whenPressed TurretBumpRight
  BACK: start whenPressed PickerToHome
  START: toggle whenPressed TurretBarfPrep

Gunner:
  BUMPER_LEFT: start whenPressed TurretBumpWheelSpeedUp
  TRIGGER_LEFT: start whenPressed TurretBumpWheelSpeedDown
  POV_UP: start whenPressed HoodBumpUp
  POV_DOWN: start whenPressed HoodBumpDown
  POV_LEFT: start whenPressed TurretBumpLeft
  POV_RIGHT: start whenPressed TurretBumpRight
  A: toggle whenPressed TurretShoot
  B: toggle whenPressed PickerPick
  Y: toggle whenPressed TurretShootPrep

defaults: [ DriveTank ]

